#!/usr/bin/bash

echo "Launch RViz ..."
gnome-terminal --tab --title="RViz" -- ros2 launch flex_bt_turtlebot2_demo_bringup rviz.launch.py use_sim_time:=${USE_SIM_TIME:=True}

echo "Wait 2 seconds for RViz startup ..."
sleep 2

echo "Launch FlexBE Mirror ..."
gnome-terminal --tab --title="FlexBE Mirror" -- ros2 run flexbe_mirror behavior_mirror_sm --ros-args --remap name:="behavior_mirror"

echo "Wait 2 seconds for Mirror startup ..."
sleep 2

echo "Launch FlexBE Behavior Launcher ..."
gnome-terminal --tab --title="FlexBE Launcher" -- ros2 run flexbe_widget be_launcher --ros-args --remap name:="behavior_launcher"

echo "Wait 2 seconds for Launcher startup ..."
sleep 2

echo "Wait 1 seconds for WebUI startup ..."
sleep 1
gnome-terminal --tab --title="FlexBE WebUI Server" -- ros2 launch flexbe_webui flexbe_ocs.launch.py headless:=True use_sim_time:=${USE_SIM_TIME:=True}

echo "Launch FlexBE WebUI client ..."
gnome-terminal --tab --title="FlexBE WebUI Client" -- ros2 run flexbe_webui webui_client use_sim_time:=${USE_SIM_TIME:=True}

echo ""

if $USE_SIM_TIME ; then
  echo "Using simulation time - should be tied to simulation not hardware!"
else
  echo ""
  echo "Using wall clock time - should be tied to hardware not simulation!"
  echo ""
fi
